CREATE TYPE "Role" AS ENUM ('ADMIN', 'CLIENT');
CREATE TYPE "RequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "AgreementStatus" AS ENUM ('OPEN', 'PAID', 'LATE', 'CANCELED');
CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Client" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "document" TEXT, "phone" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Client_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Request" ("id" TEXT NOT NULL, "clientId" TEXT NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "note" TEXT, "status" "RequestStatus" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Request_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Agreement" ("id" TEXT NOT NULL, "clientId" TEXT NOT NULL, "requestId" TEXT, "originalAmount" DECIMAL(14,2) NOT NULL, "openAmount" DECIMAL(14,2) NOT NULL, "installmentCount" INTEGER NOT NULL, "interestRate" DECIMAL(8,4) NOT NULL, "installmentAmount" DECIMAL(14,2) NOT NULL, "totalAmount" DECIMAL(14,2) NOT NULL, "agreementDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "dueDate" TIMESTAMP(3) NOT NULL, "status" "AgreementStatus" NOT NULL DEFAULT 'OPEN', "notes" TEXT, "dailyInterestRate" DECIMAL(8,4), "dailyInterestStartedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Agreement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Installment" ("id" TEXT NOT NULL, "agreementId" TEXT NOT NULL, "number" INTEGER NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "interest" DECIMAL(14,2) NOT NULL, "amortization" DECIMAL(14,2) NOT NULL, "balance" DECIMAL(14,2) NOT NULL, "dueDate" TIMESTAMP(3) NOT NULL, "paid" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "Installment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DailyInterestLog" ("id" TEXT NOT NULL, "agreementId" TEXT NOT NULL, "calculatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "days" INTEGER NOT NULL, "accumulated" DECIMAL(14,2) NOT NULL, "updatedAmount" DECIMAL(14,2) NOT NULL, CONSTRAINT "DailyInterestLog_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "Client_userId_key" ON "Client"("userId");
CREATE UNIQUE INDEX "Agreement_requestId_key" ON "Agreement"("requestId");
CREATE UNIQUE INDEX "Installment_agreementId_number_key" ON "Installment"("agreementId", "number");
ALTER TABLE "Client" ADD CONSTRAINT "Client_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Request" ADD CONSTRAINT "Request_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Agreement" ADD CONSTRAINT "Agreement_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Agreement" ADD CONSTRAINT "Agreement_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "Request"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Installment" ADD CONSTRAINT "Installment_agreementId_fkey" FOREIGN KEY ("agreementId") REFERENCES "Agreement"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DailyInterestLog" ADD CONSTRAINT "DailyInterestLog_agreementId_fkey" FOREIGN KEY ("agreementId") REFERENCES "Agreement"("id") ON DELETE CASCADE ON UPDATE CASCADE;
