"use client";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Calculator, ClipboardList, FileText, LogOut, Menu, Plus, Settings, UserRound, Users, WalletCards } from "lucide-react";
import { flatProgressiveTable, dailyInterest } from "@/lib/finance";
import type { Session } from "@/lib/auth";

type Client = { id:string; document?:string; phone?:string; user:{name:string;email:string;active:boolean}; _count?:{agreements:number;requests:number} };
type Req = { id:string; amount:string; note?:string; status:string; createdAt:string; client:{id:string;user:{name:string;email:string}} };
type Inst = { number:number;amount:string;interest:string;amortization:string;balance:string;dueDate:string };
type Agreement = { id:string;clientId:string;requestId?:string;originalAmount:string;openAmount:string;installmentCount:number;interestRate:string;installmentAmount:string;totalAmount:string;agreementDate:string;dueDate:string;status:string;notes?:string;dailyInterestRate?:string;dailyInterestStartedAt?:string;client:{user:{name:string;email:string};document?:string;phone?:string};installments:Inst[] };
const money = (v:unknown) => Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const date = (v:string) => new Date(v).toLocaleDateString("pt-BR");
const statusLabel:Record<string,string>={PENDING:"Pendente",APPROVED:"Aprovado",REJECTED:"Recusado",OPEN:"Aberto",PAID:"Pago",LATE:"Atrasado",CANCELED:"Cancelado"};
const badge=(s:string)=>s==="APPROVED"||s==="PAID"?"green":s==="REJECTED"||s==="LATE"?"red":s==="PENDING"?"amber":"blue";

async function api(url:string, options?:RequestInit){const r=await fetch(url,options);const j=await r.json();if(!r.ok)throw new Error(j.error||"Erro inesperado");return j}
export default function Dashboard({session}:{session:Session}){
 const admin=session.role==="ADMIN"; const [tab,setTab]=useState(admin?"Dashboard":"Solicitar valor"),[open,setOpen]=useState(true),[loading,setLoading]=useState(true),[clients,setClients]=useState<Client[]>([]),[requests,setRequests]=useState<Req[]>([]),[agreements,setAgreements]=useState<Agreement[]>([]),[profile,setProfile]=useState<any>(null),[modal,setModal]=useState<string|null>(null),[editing,setEditing]=useState<any>(null),[notice,setNotice]=useState("");
 const nav=admin?[ ["Dashboard",BarChart3],["Clientes",Users],["Solicitações",ClipboardList],["Calculadora",Calculator],["Relatórios",FileText],["Configurações",Settings] ]:[["Solicitar valor",WalletCards],["Meus relatórios",FileText],["Meus dados",UserRound],["Configurações",Settings]] as any;
 async function load(){setLoading(true);try{const calls=[api("/api/requests"),api("/api/agreements"),api("/api/profile")];if(admin)calls.push(api("/api/clients"));const [r,a,p,c]=await Promise.all(calls);setRequests(r);setAgreements(a);setProfile(p);if(c)setClients(c)}catch(e:any){setNotice(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function mutate(url:string,method:string,body?:any){try{await api(url,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});setModal(null);setEditing(null);setNotice("Salvo com sucesso.");await load()}catch(e:any){setNotice(e.message)}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/"}
 const title=tab; const content=loading?<div className="loading">Carregando dados...</div>:tab==="Dashboard"?<AdminHome clients={clients} requests={requests} agreements={agreements}/>:tab==="Clientes"?<Clients clients={clients} onNew={()=>{setEditing(null);setModal("client")}} onEdit={(c:any)=>{setEditing(c);setModal("client")}} onDelete={(id:string)=>confirm("Remover este cliente e seus dados?")&&mutate(`/api/clients/${id}`,"DELETE")}/>:tab==="Solicitações"?<Requests rows={requests} admin onAction={(r:any,s:string)=>s==="APPROVED"?(setEditing(r),setModal("agreement")):mutate(`/api/requests/${r.id}`,"PATCH",{status:s})}/>:tab==="Calculadora"?<LoanCalculator/>:tab==="Relatórios"||tab==="Meus relatórios"?<Agreements rows={agreements} admin={admin} clients={clients} onNew={()=>{setEditing(null);setModal("agreement")}} onEdit={(a:any)=>{setEditing(a);setModal("agreement")}} onStart={(a:any)=>mutate(`/api/agreements/${a.id}`,"PATCH",{action:"start-interest"})}/>:tab==="Solicitar valor"?<RequestValue rows={requests} submit={(d:any)=>mutate("/api/requests","POST",d)}/>:tab==="Meus dados"?<Profile data={profile}/>:<SettingsPage data={profile} save={(d:any)=>mutate("/api/profile","PATCH",d)}/>;
 return <div className="app"><div className={`mobile-overlay ${open?"":"open"}`} onClick={()=>setOpen(true)}/><aside className={`sidebar ${open?"":"open"}`}><div className="logo"><WalletCards/> Controle de Juros</div><nav className="nav">{nav.map(([name,Icon]:any)=><button key={name} className={tab===name?"active":""} onClick={()=>{setTab(name);setOpen(true)}}><Icon/>{name}</button>)}</nav><div className="user-side"><strong>{session.name}</strong>{admin?"Administrador":"Cliente"}</div><nav className="nav"><button className="logout" onClick={logout}><LogOut/>Sair</button></nav></aside><main className="main"><header className="topbar"><button className="menu-btn" onClick={()=>setOpen(!open)}><Menu/></button><h2>{title}</h2><span className="muted">{new Date().toLocaleDateString("pt-BR",{dateStyle:"long"})}</span></header><div className="content">{notice&&<div className={`alert ${notice.includes("sucesso")?"success":"error"}`} onClick={()=>setNotice("")}>{notice}</div>}{content}</div></main>{modal==="client"&&<ClientModal value={editing} close={()=>setModal(null)} save={(d:any)=>mutate(editing?`/api/clients/${editing.id}`:"/api/clients",editing?"PATCH":"POST",d)}/>} {modal==="agreement"&&<AgreementModal value={editing} clients={clients} close={()=>setModal(null)} save={(d:any,id?:string)=>mutate(id?`/api/agreements/${id}`:"/api/agreements",id?"PATCH":"POST",d)}/>}</div>
}

function Head({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="page-head"><div><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function AdminHome({clients,requests,agreements}:{clients:Client[];requests:Req[];agreements:Agreement[]}){const updated=agreements.reduce((s,a)=>s+dailyInterest(Number(a.openAmount),Number(a.dailyInterestRate),a.dailyInterestStartedAt).updatedAmount,0);return <><Head title="Visão geral" text="Acompanhe os números mais importantes do negócio."/><div className="cards"><Stat label="TOTAL DE CLIENTES" value={clients.length}/><Stat label="SOLICITAÇÕES PENDENTES" value={requests.filter(r=>r.status==="PENDING").length}/><Stat label="TOTAL EM ABERTO" value={money(agreements.filter(a=>a.status==="OPEN"||a.status==="LATE").reduce((s,a)=>s+Number(a.openAmount),0))}/><Stat label="ATUALIZADO COM JUROS" value={money(updated)}/><Stat label="RELATÓRIOS EM ATRASO" value={agreements.filter(a=>a.status==="LATE").length}/></div><div className="panel"><h3>Últimas solicitações</h3><RequestTable rows={requests.slice(0,6)}/></div></>}
function Stat({label,value}:{label:string;value:any}){return <div className="card stat"><span>{label}</span><strong>{value}</strong><i>Atualizado agora</i></div>}
function Clients({clients,onNew,onEdit,onDelete}:any){return <><Head title="Clientes" text="Cadastre e gerencie o acesso dos clientes." action={<button className="btn primary" onClick={onNew}><Plus/>Novo cliente</button>}/><div className="panel"><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Documento</th><th>Telefone</th><th>Status</th><th>Relatórios</th><th>Ações</th></tr></thead><tbody>{clients.map((c:Client)=><tr key={c.id}><td><strong>{c.user.name}</strong><span className="muted">{c.user.email}</span></td><td>{c.document||"—"}</td><td>{c.phone||"—"}</td><td><span className={`badge ${c.user.active?"green":"red"}`}>{c.user.active?"Ativo":"Inativo"}</span></td><td>{c._count?.agreements||0}</td><td className="actions"><button className="btn secondary" onClick={()=>onEdit(c)}>Editar</button><button className="btn danger" onClick={()=>onDelete(c.id)}>Remover</button></td></tr>)}</tbody></table>{!clients.length&&<div className="empty">Nenhum cliente cadastrado.</div>}</div></div></>}
function RequestTable({rows,admin,onAction}:{rows:Req[];admin?:boolean;onAction?:(r:Req,s:string)=>void}){return <div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Valor</th><th>Data</th><th>Observação</th><th>Status</th>{admin&&<th>Ações</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.client.user.name}</strong></td><td>{money(r.amount)}</td><td>{date(r.createdAt)}</td><td>{r.note||"—"}</td><td><span className={`badge ${badge(r.status)}`}>{statusLabel[r.status]}</span></td>{admin&&<td className="actions">{r.status==="PENDING"&&<><button className="btn success" onClick={()=>onAction?.(r,"APPROVED")}>Aprovar</button><button className="btn danger" onClick={()=>onAction?.(r,"REJECTED")}>Recusar</button></>}</td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty">Nenhuma solicitação encontrada.</div>}</div>}
function Requests({rows,admin,onAction}:any){return <><Head title="Solicitações" text="Analise os pedidos enviados pelos clientes."/><div className="panel"><RequestTable rows={rows} admin={admin} onAction={onAction}/></div></>}
function RequestValue({rows,submit}:any){return <><Head title="Solicitar valor" text="Envie uma nova solicitação ao administrador."/><div className="panel" style={{maxWidth:650}}><form onSubmit={e=>{e.preventDefault();submit(Object.fromEntries(new FormData(e.currentTarget)))}}><div className="field"><label>Valor desejado</label><input type="number" name="amount" min="0.01" step="0.01" required placeholder="0,00"/></div><div className="field"><label>Observação ou motivo</label><textarea name="note" placeholder="Conte como pretende utilizar o valor..."/></div><button className="btn primary">Enviar solicitação</button></form></div><div className="panel"><h3>Histórico</h3><RequestTable rows={rows}/></div></>}

function LoanCalculator(){const [p,setP]=useState(100),[rate,setRate]=useState(40),[count,setCount]=useState(1),[extra,setExtra]=useState(5);const calc=useMemo(()=>{try{return flatProgressiveTable(p,rate,count,extra)}catch{return null}},[p,rate,count,extra]);return <><Head title="Calculadora" text="Simule com juros fixo padrão de 40% e adicional progressivo a partir da 3ª parcela."/><div className="calc-grid"><div className="panel"><div className="field"><label>Valor</label><input type="number" min="0.01" step="0.01" value={p} onChange={e=>setP(Number(e.target.value))}/></div><div className="field"><label>Juros base (%)</label><input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(Number(e.target.value))}/></div><div className="field"><label>Quantidade de parcelas</label><input type="number" min="1" value={count} onChange={e=>setCount(Math.max(1,Number(e.target.value)))}/></div><div className="field"><label>Adicional por parcela após a 2ª (%)</label><input type="number" min="0" step="0.01" value={extra} onChange={e=>setExtra(Number(e.target.value))}/></div><p className="muted">Exemplo: R$ 100,00 em 1x = R$ 140,00. Em 2x = 2 parcelas de R$ 70,00.</p></div><div className="panel"><h3>Resultado da simulação</h3>{calc&&<><div className="summary"><div><span>VALOR DA PARCELA</span><strong>{money(calc.payment)}</strong></div><div><span>TOTAL FINAL</span><strong>{money(calc.total)}</strong></div><div><span>JUROS APLICADO</span><strong>{calc.effectiveRate}%</strong></div></div><Schedule rows={calc.rows}/></>}</div></div></>}
function Schedule({rows}:{rows:any[]}){return <div className="table-wrap"><table><thead><tr><th>Parcela</th><th>Valor</th><th>Juros</th><th>Amortização</th><th>Saldo devedor</th></tr></thead><tbody>{rows.map(r=><tr key={r.number}><td>{r.number}</td><td>{money(r.amount)}</td><td>{money(r.interest)}</td><td>{money(r.amortization)}</td><td>{money(r.balance)}</td></tr>)}</tbody></table></div>}

function Agreements({rows,admin,clients,onNew,onEdit,onStart}:any){const [filter,setFilter]=useState("");const shown=filter?rows.filter((a:Agreement)=>a.clientId===filter):rows;return <><Head title={admin?"Relatórios e acordos":"Meus relatórios"} text={admin?"Acordos financeiros separados por cliente.":"Consulte seus acordos e valores atualizados."} action={admin?<button className="btn primary" onClick={onNew}><Plus/>Novo acordo</button>:undefined}/>{admin&&<div className="toolbar" style={{marginBottom:16}}><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos os clientes</option>{clients.map((c:Client)=><option value={c.id} key={c.id}>{c.user.name}</option>)}</select><button className="btn secondary" onClick={()=>pdfAll(shown,"Relatório geral")}>Gerar PDF geral</button></div>}<div className="panel"><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Valor original</th><th>Parcelas</th><th>Total</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{shown.map((a:Agreement)=><tr key={a.id}><td><strong>{a.client.user.name}</strong></td><td>{money(a.originalAmount)}</td><td>{a.installmentCount} × {money(a.installmentAmount)}</td><td>{money(dailyInterest(Number(a.openAmount),Number(a.dailyInterestRate),a.dailyInterestStartedAt).updatedAmount)}</td><td>{date(a.dueDate)}</td><td><span className={`badge ${badge(a.status)}`}>{statusLabel[a.status]}</span></td><td className="actions"><button className="btn secondary" onClick={()=>pdfAgreement(a)}>PDF</button>{admin&&<><button className="btn secondary" onClick={()=>onEdit(a)}>Editar</button>{!a.dailyInterestStartedAt&&Number(a.dailyInterestRate)>0&&<button className="btn success" onClick={()=>onStart(a)}>Iniciar juros diário</button>}</>}</td></tr>)}</tbody></table>{!shown.length&&<div className="empty">Nenhum relatório encontrado.</div>}</div></div>{shown.map((a:Agreement)=><AgreementDetail key={a.id} a={a}/>)}</>}
function AgreementDetail({a}:{a:Agreement}){const d=dailyInterest(Number(a.openAmount),Number(a.dailyInterestRate),a.dailyInterestStartedAt);return <div className="panel"><h3>{a.client.user.name} — acordo de {date(a.agreementDate)}</h3><div className="detail-grid"><div><span>Valor original</span><strong>{money(a.originalAmount)}</strong></div><div><span>Valor em aberto</span><strong>{money(a.openAmount)}</strong></div><div><span>Taxa mensal</span><strong>{Number(a.interestRate)}%</strong></div><div><span>Valor atualizado</span><strong>{money(d.updatedAmount)}</strong></div></div>{a.dailyInterestStartedAt&&<div className="interest-box"><strong>Juros diário em andamento</strong><div className="detail-grid" style={{marginTop:10}}><div><span>Taxa diária</span><strong>{Number(a.dailyInterestRate)}%</strong></div><div><span>Início</span><strong>{date(a.dailyInterestStartedAt)}</strong></div><div><span>Dias corridos</span><strong>{d.days}</strong></div><div><span>Juros acumulado</span><strong>{money(d.accumulated)}</strong></div></div></div>}</div>}

function ClientModal({value,close,save}:any){return <Modal title={value?"Editar cliente":"Novo cliente"} close={close}><form className="grid-form" onSubmit={e=>{e.preventDefault();const d:any=Object.fromEntries(new FormData(e.currentTarget));d.active=d.active==="on";save(d)}}><Field label="Nome completo"><input name="name" required defaultValue={value?.user.name}/></Field><Field label="Login do cliente"><input type="text" name="email" required minLength={3} autoComplete="username" defaultValue={value?.user.email}/></Field><Field label={value?"Nova senha (opcional)":"Senha inicial"}><input type="password" name="password" required={!value} minLength={6}/></Field><Field label="CPF/CNPJ (opcional)"><input name="document" defaultValue={value?.document}/></Field><Field label="Telefone (opcional)"><input name="phone" defaultValue={value?.phone}/></Field><Field label="Situação"><label style={{fontWeight:400}}><input type="checkbox" name="active" defaultChecked={value?value.user.active:true} style={{width:"auto"}}/> Cliente ativo</label></Field><div className="span3 actions"><button type="button" className="btn secondary" onClick={close}>Cancelar</button><button className="btn primary">Salvar cliente</button></div></form></Modal>}
function AgreementModal({value,clients,close,save}:any){const request=value?.client?value:null;const agreement=value?.installments?value:null;const clientId=agreement?.clientId||request?.client?.id||"";return <Modal title={agreement?"Editar relatório":"Novo acordo"} close={close}><form className="grid-form" onSubmit={e=>{e.preventDefault();const d:any=Object.fromEntries(new FormData(e.currentTarget));save(d,agreement?.id)}}><Field label="Cliente"><select name="clientId" required defaultValue={clientId} disabled={!!agreement}>{!clientId&&<option value="">Selecione</option>}{clients.map((c:Client)=><option key={c.id} value={c.id}>{c.user.name}</option>)}</select></Field><Field label="Valor original"><input name="originalAmount" type="number" min="0.01" step="0.01" required defaultValue={agreement?.originalAmount||request?.amount}/></Field><Field label="Valor em aberto"><input name="openAmount" type="number" min="0.01" step="0.01" defaultValue={agreement?.openAmount||request?.amount}/></Field><Field label="Quantidade de parcelas"><input name="installmentCount" type="number" min="1" required defaultValue={agreement?.installmentCount||12}/></Field><Field label="Juros mensal (%)"><input name="interestRate" type="number" min="0" step="0.0001" required defaultValue={agreement?.interestRate||2}/></Field><Field label="Juros diário (%)"><input name="dailyInterestRate" type="number" min="0" step="0.0001" defaultValue={agreement?.dailyInterestRate||0}/></Field><Field label="Vencimento"><input name="dueDate" type="date" required defaultValue={agreement?agreement.dueDate.slice(0,10):""}/></Field>{agreement&&<Field label="Status"><select name="status" defaultValue={agreement.status}><option value="OPEN">Aberto</option><option value="PAID">Pago</option><option value="LATE">Atrasado</option><option value="CANCELED">Cancelado</option></select></Field>}<div className="field span3"><label>Observações</label><textarea name="notes" defaultValue={agreement?.notes||request?.note}/></div>{request&&!agreement&&<input type="hidden" name="requestId" value={request.id}/>}<div className="span3 actions"><button type="button" className="btn secondary" onClick={close}>Cancelar</button><button className="btn primary">Salvar e calcular</button></div></form></Modal>}
function Modal({title,close,children}:any){return <div className="modal-bg"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
function Profile({data}:any){return <><Head title="Meus dados" text="Informações vinculadas ao seu acesso."/><div className="panel" style={{maxWidth:650}}><div className="detail-grid"><div><span>Nome</span><strong>{data?.name}</strong></div><div><span>Login</span><strong>{data?.email}</strong></div><div><span>CPF/CNPJ</span><strong>{data?.client?.document||"Não informado"}</strong></div><div><span>Telefone</span><strong>{data?.client?.phone||"Não informado"}</strong></div></div></div></>}
function SettingsPage({data,save}:any){return <><Head title="Configurações" text="Atualize seu login e senha de acesso."/><div className="panel" style={{maxWidth:650}}><form className="grid-form" onSubmit={e=>{e.preventDefault();const d:any=Object.fromEntries(new FormData(e.currentTarget));save(d)}}><Field label="Nome completo"><input name="name" required minLength={2} defaultValue={data?.name}/></Field><Field label="Login de acesso"><input name="email" required minLength={3} autoComplete="username" defaultValue={data?.email}/></Field><Field label="Nova senha (opcional)"><input name="password" type="password" minLength={6} autoComplete="new-password" placeholder="Deixe em branco para manter"/></Field><div className="span3 actions"><button className="btn primary">Salvar configurações</button></div></form></div></>}

async function pdfAgreement(a:Agreement){const {jsPDF}=await import("jspdf");const autoTable=(await import("jspdf-autotable")).default;const doc=new jsPDF();const d=dailyInterest(Number(a.openAmount),Number(a.dailyInterestRate),a.dailyInterestStartedAt);doc.setFillColor(12,29,54);doc.rect(0,0,210,32,"F");doc.setTextColor(255,255,255);doc.setFontSize(20);doc.text("Controle de Juros",14,20);doc.setTextColor(25,35,52);doc.setFontSize(14);doc.text("Relatório de acordo",14,45);doc.setFontSize(10);doc.text([`Cliente: ${a.client.user.name}`,`Login: ${a.client.user.email}`,`Documento: ${a.client.document||"Não informado"}`,`Emissão: ${new Date().toLocaleDateString("pt-BR")}`,`Valor original: ${money(a.originalAmount)}`,`Parcelas: ${a.installmentCount} de ${money(a.installmentAmount)}`,`Juros mensal: ${Number(a.interestRate)}%`,`Juros diário: ${Number(a.dailyInterestRate||0)}%`,`Valor atualizado: ${money(d.updatedAmount)}`,`Status: ${statusLabel[a.status]}`,`Observações: ${a.notes||"—"}`],14,55);autoTable(doc,{startY:105,head:[["Parcela","Valor","Juros","Amortização","Saldo"]],body:a.installments.map(i=>[i.number,money(i.amount),money(i.interest),money(i.amortization),money(i.balance)]),styles:{fontSize:8},headStyles:{fillColor:[37,99,235]}});doc.save(`acordo-${a.client.user.name.replace(/\s+/g,"-").toLowerCase()}.pdf`)}
async function pdfAll(rows:Agreement[],title:string){const {jsPDF}=await import("jspdf");const autoTable=(await import("jspdf-autotable")).default;const doc=new jsPDF();doc.setFontSize(18);doc.text(`Controle de Juros — ${title}`,14,20);doc.setFontSize(9);doc.text(`Emitido em ${new Date().toLocaleString("pt-BR")}`,14,27);autoTable(doc,{startY:34,head:[["Cliente","Original","Parcelas","Atualizado","Vencimento","Status"]],body:rows.map(a=>[a.client.user.name,money(a.originalAmount),a.installmentCount,money(dailyInterest(Number(a.openAmount),Number(a.dailyInterestRate),a.dailyInterestStartedAt).updatedAmount),date(a.dueDate),statusLabel[a.status]]),styles:{fontSize:8},headStyles:{fillColor:[12,29,54]}});doc.save("relatorio-geral.pdf")}
